In [1]:
import pandas as pd
import numpy as np
from numpy import unravel_index

1. order - 블럭장난감 일별 수요    
2. stock - 보유 각 아이템 재고    
3. max_count - 성형 공정 일별 최대 투입 개수    
4. change_time - 변경에 필요한 시간    
5. cut_yield - 자르기 공정의 각 아이템 월별 양품률   
6. sample_submission

In [2]:
order = pd.read_csv('data/order.csv')
stock = pd.read_csv('data/stock.csv')
max_count = pd.read_csv('data/max_count.csv')
cut_yield = pd.read_csv('data/cut_yield.csv')
change_time =pd.read_csv('data/change_time.csv')
sample_submission = pd.read_csv('data/sample_submission.csv')
order

          time  BLK_1  BLK_2  BLK_3  BLK_4
0   2020-04-01      0      0      0      0
1   2020-04-02      0      0      0      0
2   2020-04-03      0      0      0      0
3   2020-04-04      0      0      0      0
4   2020-04-05      0      0      0      0
5   2020-04-06      0      0      0      0
6   2020-04-07      0      0      0      0
7   2020-04-08      0      0      0      0
8   2020-04-09      0      0      0      0
9   2020-04-10      0      0      0      0
10  2020-04-11      0      0      0      0
11  2020-04-12      0      0      0      0
12  2020-04-13      0      0      0      0
13  2020-04-14      0      0      0      0
14  2020-04-15      0  18018      0      0
15  2020-04-16      0  20437      0      0
16  2020-04-17      0  12059      0      0
17  2020-04-18      0  12059      0      0
18  2020-04-19      0  12059      0      0
19  2020-04-20      0  12059      0      0
20  2020-04-21      0  12059      0      0
21  2020-04-22      0  12059      0      0
22  2020-04-23      0  12059      0      0
23  2020-04-24      0   2954      0      0
24  2020-04-25      0      0      0      0
25  2020-04-26      0      0      0      0
26  2020-04-27      0      0      0      0
27  2020-04-28      0      0      0      0
28  2020-04-29      0      0      0      0
29  2020-04-30      0      0      0      0
..         ...    ...    ...    ...    ...
61  2020-06-01  15588      0  30756  10349
62  2020-06-02  15937      0  31456      0
63  2020-06-03  15937      0  15728  10349
64  2020-06-04  15937      0  15728  20697
65  2020-06-05  31874      0  20970  20697
66  2020-06-06  31874      0  20970  20697
67  2020-06-07  31874      0  20970  20697
68  2020-06-08  31874      0  10485  20697
69  2020-06-09  31874      0  10485      0
70  2020-06-10  15937      0   5243  20697
71  2020-06-11  15937      0   5243  20697
72  2020-06-12  31874      0  20970  20697
73  2020-06-13  31874      0  20970  41395
74  2020-06-14  31874      0  20970  41395
75  2020-06-15  31874      0  62911  41395
76  2020-06-16  31874      0  62911      0
77  2020-06-17  21250      0  31456  41395
78  2020-06-18  21250      0  31456  41395
79  2020-06-19  42499      0  62911  41395
80  2020-06-20  42499      0  41941  41395
81  2020-06-21  42499      0  41941  41395
82  2020-06-22  42499      0  41941  62092
83  2020-06-23  42499      0  62911      0
84  2020-06-24  21250      0  31456  62092
85  2020-06-25  21250      0  31456  62092
86  2020-06-26  42499      0  62911  62092
87  2020-06-27  42499      0  41941  62092
88  2020-06-28  42499      0  41941  62092
89  2020-06-29  42499      0  41941  31046
90  2020-06-30  42499      0  62911      0

[91 rows x 5 columns]

In [3]:
stock

,PRT_1,PRT_2,PRT_3,PRT_4,MOL_1,MOL_2,MOL_3,MOL_4,BLK_1,BLK_2,BLK_3,BLK_4
0,0,258,0,0,1086,0,0,0,61158,87279,0,0

In [4]:
order

          time  BLK_1  BLK_2  BLK_3  BLK_4
0   2020-04-01      0      0      0      0
1   2020-04-02      0      0      0      0
2   2020-04-03      0      0      0      0
3   2020-04-04      0      0      0      0
4   2020-04-05      0      0      0      0
5   2020-04-06      0      0      0      0
6   2020-04-07      0      0      0      0
7   2020-04-08      0      0      0      0
8   2020-04-09      0      0      0      0
9   2020-04-10      0      0      0      0
10  2020-04-11      0      0      0      0
11  2020-04-12      0      0      0      0
12  2020-04-13      0      0      0      0
13  2020-04-14      0      0      0      0
14  2020-04-15      0  18018      0      0
15  2020-04-16      0  20437      0      0
16  2020-04-17      0  12059      0      0
17  2020-04-18      0  12059      0      0
18  2020-04-19      0  12059      0      0
19  2020-04-20      0  12059      0      0
20  2020-04-21      0  12059      0      0
21  2020-04-22      0  12059      0      0
22  2020-04-23      0  12059      0      0
23  2020-04-24      0   2954      0      0
24  2020-04-25      0      0      0      0
25  2020-04-26      0      0      0      0
26  2020-04-27      0      0      0      0
27  2020-04-28      0      0      0      0
28  2020-04-29      0      0      0      0
29  2020-04-30      0      0      0      0
..         ...    ...    ...    ...    ...
61  2020-06-01  15588      0  30756  10349
62  2020-06-02  15937      0  31456      0
63  2020-06-03  15937      0  15728  10349
64  2020-06-04  15937      0  15728  20697
65  2020-06-05  31874      0  20970  20697
66  2020-06-06  31874      0  20970  20697
67  2020-06-07  31874      0  20970  20697
68  2020-06-08  31874      0  10485  20697
69  2020-06-09  31874      0  10485      0
70  2020-06-10  15937      0   5243  20697
71  2020-06-11  15937      0   5243  20697
72  2020-06-12  31874      0  20970  20697
73  2020-06-13  31874      0  20970  41395
74  2020-06-14  31874      0  20970  41395
75  2020-06-15  31874      0  62911  41395
76  2020-06-16  31874      0  62911      0
77  2020-06-17  21250      0  31456  41395
78  2020-06-18  21250      0  31456  41395
79  2020-06-19  42499      0  62911  41395
80  2020-06-20  42499      0  41941  41395
81  2020-06-21  42499      0  41941  41395
82  2020-06-22  42499      0  41941  62092
83  2020-06-23  42499      0  62911      0
84  2020-06-24  21250      0  31456  62092
85  2020-06-25  21250      0  31456  62092
86  2020-06-26  42499      0  62911  62092
87  2020-06-27  42499      0  41941  62092
88  2020-06-28  42499      0  41941  62092
89  2020-06-29  42499      0  41941  31046
90  2020-06-30  42499      0  62911      0

[91 rows x 5 columns]

In [5]:
word = 'change13'
print(int(word[6]) + int(word[7]))

int(change_time[(change_time['from'] == 'MOL_'+word[6]) & (change_time['to'] == 'MOL_' +word[7])]['time'])

4

13

In [6]:
change_time

     from     to  time
0   MOL_1  MOL_2     6
1   MOL_1  MOL_3    13
2   MOL_1  MOL_4    13
3   MOL_2  MOL_1     6
4   MOL_2  MOL_3    13
5   MOL_2  MOL_4    13
6   MOL_3  MOL_1    13
7   MOL_3  MOL_2    13
8   MOL_3  MOL_4     6
9   MOL_4  MOL_1    13
10  MOL_4  MOL_2    13
11  MOL_4  MOL_3     6

In [7]:
sample_submission

,time,PRT_1,PRT_2,PRT_3,PRT_4,Event_A,MOL_A,Event_B,MOL_B
0,2020-04-01 00:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
1,2020-04-01 01:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
2,2020-04-01 02:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
3,2020-04-01 03:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
4,2020-04-01 04:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
5,2020-04-01 05:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
6,2020-04-01 06:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
7,2020-04-01 07:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
8,2020-04-01 08:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
9,2020-04-01 09:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
10,2020-04-01 10:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
11,2020-04-01 11:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
12,2020-04-01 12:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
13,2020-04-01 13:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
14,2020-04-01 14:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
15,2020-04-01 15:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
16,2020-04-01 16:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
17,2020-04-01 17:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
18,2020-04-01 18:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
19,2020-04-01 19:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
20,2020-04-01 20:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
21,2020-04-01 21:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
22,2020-04-01 22:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
23,2020-04-01 23:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
24,2020-04-02 00:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
25,2020-04-02 01:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
26,2020-04-02 02:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
27,2020-04-02 03:00:00,0,0,0,0,CHECK_1,0,CHECK_1,0
28,2020-04-02 04:00:00,0,0,0,0,PROCESS,0,PROCESS,0
29,2020-04-02 05:00:00,0,0,0,0,PROCESS,0,PROCESS,0
...,...,...,...,...,...,...,...,...,...
2154,2020-06-29 18:00:00,0,0,0,0,STOP,0,STOP,0
2155,2020-06-29 19:00:00,0,0,0,0,STOP,0,STOP,0
2156,2020-06-29 20:00:00,0,0,0,0,STOP,0,STOP,0
2157,2020-06-29 21:00:00,0,0,0,0,STOP,0,STOP,0
2158,2020-06-29 22:00:00,0,0,0,0,STOP,0,STOP,0
2159,2020-06-29 23:00:00,0,0,0,0,STOP,0,STOP,0
2160,2020-06-30 00:00:00,0,0,0,0,STOP,0,STOP,0
2161,2020-06-30 01:00:00,0,0,0,0,STOP,0,STOP,0
2162,2020-06-30 02:00:00,0,0,0,0,STOP,0,STOP,0
2163,2020-06-30 03:00:00,0,0,0,0,STOP,0,STOP,0
2164,2020-06-30 04:00:00,0,0,0,0,STOP,0,STOP,0
2165,2020-06-30 05:00:00,0,0,0,0,STOP,0,STOP,0
2166,2020-06-30 06:00:00,0,0,0,0,STOP,0,STOP,0
2167,2020-06-30 07:00:00,0,0,0,0,STOP,0,STOP,0
2168,2020-06-30 08:00:00,0,0,0,0,STOP,0,STOP,0
2169,2020-06-30 09:00:00,0,0,0,0,STOP,0,STOP,0
2170,2020-06-30 10:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2171,2020-06-30 11:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2172,2020-06-30 12:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2173,2020-06-30 13:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2174,2020-06-30 14:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2175,2020-06-30 15:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2176,2020-06-30 16:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2177,2020-06-30 17:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2178,2020-06-30 18:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2179,2020-06-30 19:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2180,2020-06-30 20:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2181,2020-06-30 21:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2182,2020-06-30 22:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0
2183,2020-06-30 23:00:00,0,0,0,0,CHECK_3,0,CHECK_3,0

In [8]:
pd.set_option('display.max_rows', 2000)

In [9]:
order['BLK_1'] = order['BLK_1'] /506
order['BLK_2'] = order['BLK_2'] /506
order['BLK_3'] = order['BLK_3'] /400
order['BLK_4'] = order['BLK_4'] /400

In [10]:
order

          time      BLK_1      BLK_2     BLK_3     BLK_4
0   2020-04-01   0.000000   0.000000    0.0000    0.0000
1   2020-04-02   0.000000   0.000000    0.0000    0.0000
2   2020-04-03   0.000000   0.000000    0.0000    0.0000
3   2020-04-04   0.000000   0.000000    0.0000    0.0000
4   2020-04-05   0.000000   0.000000    0.0000    0.0000
5   2020-04-06   0.000000   0.000000    0.0000    0.0000
6   2020-04-07   0.000000   0.000000    0.0000    0.0000
7   2020-04-08   0.000000   0.000000    0.0000    0.0000
8   2020-04-09   0.000000   0.000000    0.0000    0.0000
9   2020-04-10   0.000000   0.000000    0.0000    0.0000
10  2020-04-11   0.000000   0.000000    0.0000    0.0000
11  2020-04-12   0.000000   0.000000    0.0000    0.0000
12  2020-04-13   0.000000   0.000000    0.0000    0.0000
13  2020-04-14   0.000000   0.000000    0.0000    0.0000
14  2020-04-15   0.000000  35.608696    0.0000    0.0000
15  2020-04-16   0.000000  40.389328    0.0000    0.0000
16  2020-04-17   0.000000  23.832016    0.0000    0.0000
17  2020-04-18   0.000000  23.832016    0.0000    0.0000
18  2020-04-19   0.000000  23.832016    0.0000    0.0000
19  2020-04-20   0.000000  23.832016    0.0000    0.0000
20  2020-04-21   0.000000  23.832016    0.0000    0.0000
21  2020-04-22   0.000000  23.832016    0.0000    0.0000
22  2020-04-23   0.000000  23.832016    0.0000    0.0000
23  2020-04-24   0.000000   5.837945    0.0000    0.0000
24  2020-04-25   0.000000   0.000000    0.0000    0.0000
25  2020-04-26   0.000000   0.000000    0.0000    0.0000
26  2020-04-27   0.000000   0.000000    0.0000    0.0000
27  2020-04-28   0.000000   0.000000    0.0000    0.0000
28  2020-04-29   0.000000   0.000000    0.0000    0.0000
29  2020-04-30   0.000000   0.000000    0.0000    0.0000
30  2020-05-01   0.000000   0.000000    0.0000    0.0000
31  2020-05-02   0.000000   0.000000    0.0000    0.0000
32  2020-05-03   0.000000   0.000000    0.0000    0.0000
33  2020-05-04   0.000000   0.000000    0.0000    0.0000
34  2020-05-05   0.000000   0.000000    0.0000    0.0000
35  2020-05-06   0.000000  24.928854    0.0000    0.0000
36  2020-05-07   0.000000  24.928854    0.0000    0.0000
37  2020-05-08   0.000000  49.857708    0.0000    0.0000
38  2020-05-09   0.000000  49.857708    0.0000    0.0000
39  2020-05-10   0.000000  49.857708    0.0000    0.0000
40  2020-05-11   0.000000  34.960474    0.0000    0.0000
41  2020-05-12   0.000000   0.000000    0.0000    0.0000
42  2020-05-13   0.000000   0.000000    0.0000    0.0000
43  2020-05-14   0.000000   0.000000    0.0000    0.0000
44  2020-05-15   0.000000   0.000000    0.0000    0.0000
45  2020-05-16   0.000000   0.000000    0.0000    0.0000
46  2020-05-17   0.000000   0.000000    0.0000    0.0000
47  2020-05-18   0.000000   0.000000    0.0000    0.0000
48  2020-05-19   0.000000   0.000000    0.0000    0.0000
49  2020-05-20   0.000000   0.000000    0.0000    0.0000
50  2020-05-21   0.000000   0.000000    0.0000    0.0000
51  2020-05-22   0.000000   0.000000    0.0000    0.0000
52  2020-05-23   0.000000   0.000000    0.0000    0.0000
53  2020-05-24   0.000000   0.000000    0.0000    0.0000
54  2020-05-25   0.000000   0.000000    0.0000    0.0000
55  2020-05-26   0.000000   0.000000   51.2600    0.0000
56  2020-05-27   0.000000   0.000000   38.4450    0.0000
57  2020-05-28   0.000000   0.000000   38.4450    0.0000
58  2020-05-29   0.000000   0.000000   38.4450    0.0000
59  2020-05-30  61.610672   0.000000   38.4450    0.0000
60  2020-05-31  61.610672   0.000000   38.4450    0.0000
61  2020-06-01  30.806324   0.000000   76.8900   25.8725
62  2020-06-02  31.496047   0.000000   78.6400    0.0000
63  2020-06-03  31.496047   0.000000   39.3200   25.8725
64  2020-06-04  31.496047   0.000000   39.3200   51.7425
65  2020-06-05  62.992095   0.000000   52.4250   51.7425
66  2020-06-06  62.992095   0.000000   52.4250   51.7425
67  2020-06-07  62.992095   0.000000   52.4250   51.7425
68  2020-06-08  62.992095   0.000000   26.2125   51.7425
69  2020-06-09  62.992095   0.000000   26.2125    0.0000
70  2020-06-10  31.496047   0.000000   13.1075   51.7425
71  2020-06-11  31.496047   0.000000   13.1075   51.7425
72  2020-06-12  62.992095   0.000000   52.4250   51.7425
73  2020-06-13  62.992095   0.000000   52.4250  103.4875
74  2020-06-14  62.992095   0.000000   52.4250  103.4875
75  2020-06-15  62.992095   0.000000  157.2775  103.4875
76  2020-06-16  62.992095   0.000000  157.2775    0.0000
77  2020-06-17  41.996047   0.000000   78.6400  103.4875
78  2020-06-18  41.996047   0.000000   78.6400  103.4875
79  2020-06-19  83.990119   0.000000  157.2775  103.4875
80  2020-06-20  83.990119   0.000000  104.8525  103.4875
81  2020-06-21  83.990119   0.000000  104.8525  103.4875
82  2020-06-22  83.990119   0.000000  104.8525  155.2300
83  2020-06-23  83.990119   0.000000  157.2775    0.0000
84  2020-06-24  41.996047   0.000000   78.6400  155.2300
85  2020-06-25  41.996047   0.000000   78.6400  155.2300
86  2020-06-26  83.990119   0.000000  157.2775  155.2300
87  2020-06-27  83.990119   0.000000  104.8525  155.2300
88  2020-06-28  83.990119   0.000000  104.8525  155.2300
89  2020-06-29  83.990119   0.000000  104.8525   77.6150
90  2020-06-30  83.990119   0.000000  157.2775    0.0000

In [11]:
import pandas as pd
import numpy as np
import multiprocessing
import warnings
from copy import deepcopy
from module.genome import Genome, genome_score
warnings.filterwarnings(action='ignore')
np.random.seed(777)

ModuleNotFoundError: No module named 'module'

In [ ]:
max_count.head()

In [ ]:
max_count.loc[2183//24, 'count']

In [ ]:
6.667 *21

In [ ]:
change_time

2184개 t

In [ ]:
import os
import pandas as pd
import numpy as np
from pandas.api.types import is_numeric_dtype
from pathlib import Path

In [ ]:
class simulator:
    def __init__(self):
        self.sample_submission = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'sample_submission.csv'))
        self.max_count = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'max_count.csv'))
        self.stock = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'stock.csv'))
        order = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'order.csv'), index_col=0)   
        order.index = pd.to_datetime(order.index)
        self.order = order
        
    def get_state(self, data):
        if 'CHECK' in data:
            return int(data[-1])
        elif 'CHANGE' in data:
            return int(data[-1])
        else:
            return np.nan

In [ ]:
class RL :
    def __init__(self):
        self.sample_submission = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'sample_submission.csv'))
        self.max_count = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'max_count.csv'))
        self.stock = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'stock.csv'))
        order = pd.read_csv(os.path.join(Path(__file__).resolve().parent, 'order.csv'), index_col=0)
        order['BLK_1'] = order['BLK_1'] /506
        order['BLK_2'] = order['BLK_2'] /506
        order['BLK_3'] = order['BLK_3'] /400
        order['BLK_4'] = order['BLK_4'] /400
        self.order = order
        self.state = [2183, self.max_count.loc[2182//24, 'count'], self.order.loc[2182//24, 'BLK_1'], \
                      self.order.loc[2182//24, 'BLK_2'] ,self.order.loc[2182//24, 'BLK_3'], self.order.loc[2182//24, 'BLK_4'],\
                     0, 0 ,0 ] ## process_time checker, check_time_checker, change_time_checker 
        self.production = [0,0,0,0]
        self.checker2 = [0,0,0,0] # 성형공정변경시간 합계 , 변경 이벤트, 멈춤시간합계, 멈춤이벤트
        
        
    def get_state(self, last_state) : ## 현재 시간과 t+1의 state를 받아서 t의 state를 계산
        t = last_state[0] - 1
        
        # 날짜별 최대 투입 수
        day = t // 24
        if day != (last_state[0])//24 :
            remain_day_max = max_count.loc[t//24, 'count']
        else: 
            remain_day_max = last_state[1] -6.667
        
        # 최소 작업시간, 최대 작업시간
        remain_work_time = last_state[2] 
        
        state = []   # state에 넣을 데이터 [시간, remain_day_max, 밑에서부터 작업시간]
        return 
    
    def update_state(self, last_state):
        t = last_state[0] - 1
        day = t//24
        
        if day != (last_state[0])//24 :
            remain_day_max = max_count.loc[t//24, 'count']
        else: 
            remain_day_max = last_state[1] -6.667
            
    def F(x, a):
        if x < a:
            return 1 - x/a
        else :
            return 0
        
    def Reward(self) :
        p = max(self.order.loc[(self.state[0] // 24):, 'BLK_1'].sum() - self.production[0], 0)+ \
        max(self.order.loc[(self.state[0] // 24):, 'BLK_2'].sum() - self.production[1], 0)+ \
        max(self.order.loc[(self.state[0] // 24):, 'BLK_3'].sum() - self.production[2], 0)+ \
        max(self.order.loc[(self.state[0] // 24):, 'BLK_4'].sum() - self.production[3], 0)
         # 역누적 수요 -역누적 생산량 = 부족분
            
        q = max(self.production[0] - self.order.loc[(self.state[0] // 24):, 'BLK_1'].sum(), 0)+ \
        max(self.production[1] - self.order.loc[(self.state[0] // 24):, 'BLK_2'].sum(), 0)+ \
        max(self.production[2] - self.order.loc[(self.state[0] // 24):, 'BLK_3'].sum(), 0)+ \
        max(self.production[3] - self.order.loc[(self.state[0] // 24):, 'BLK_4'].sum(), 0) 
        # 역누적 생산 - 역누적 수요 = 과잉분
        
        c = self.checker2[0]
        c_n = self.checker2[1]
        s = self.checker2[2]
        s_n = self.checker2[3]
        
        N = self.order.loc[(self.state[0]//24):, ['BLK_1','BLK_2','BLK-3','BLK-4']].sum().sum()
        M = 2184- self.state[0]
        
        score = 50 * F(p, 10*N) + 20 * F(q, 10*N) + 20 * F(c, M) / (1+0.1 * c_n) + 10 * F(s, M) / (1+0.1 * s_n)
        return score
    
    
    def action_candidate(self):
        state = self.state
        checker2 = self.checker2
        change_list = ['change12', 'change13','change14', 'change23']
        candidate_list = []
        if state[0] <= 27 :
            candidate_list += ["check1", "check2","check3","check4", "stop"]
        elif state[6] >= 42 :
            candidate_list += ['process','change12']
        elif state[6] <= 0 : 
            candidate_list += ['check1','check2','check3','check4','stop']

State = (t, max_count 얼마나 남았는지, 납기기한, check time checker, process time checker, chagne time checker)

In [ ]:
F(x, a): 1 - x/a if x < a else 0

In [ ]:
a = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a.loc[1: , [0,1]].sum().sum()

In [ ]:
1e8

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
!pip uninstall tensorflow

In [ ]:
!pip install tensorflow==2.2.0

In [ ]:
from numpy import unravel_index
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.layers import Conv2D, Activation, MaxPooling2D, Dropout, Dense, Flatten, Conv1D, MaxPooling1D
class DACON():
    def __init__(self):
        self.sample_submission = pd.read_csv('data/sample_submission.csv')
        self.max_count = pd.read_csv('data/max_count.csv')
        self.stock = pd.read_csv('data/stock.csv')
        self.order = pd.read_csv('data/order.csv')
        self.change_time = pd.read_csv('data/change_time.csv')
        self.production = [0,0,0,0]
        self.checker2 = [0,0,0,0] # 성형공정변경시간 합계 , 변경 이벤트, 멈춤시간합계, 멈춤이벤트
        
        
        
        self.action_dict = {0:'PROCESS', 1:'STOP',2:'CHECK1', 3 : 'CHECK2', 4 : 'CHECK3' , 5 : 'CHECK4', 6 : 'CHANGE12', 7 : 'CHANGE13'
              ,8 : 'CHANGE14' , 9: 'CHANGE21', 10 : 'CHANGE23', 11 : 'CHANGE24', 12:'CHANGE31', 13: 'CHANGE32',14:'CHANGE34',
              15 : 'CHANGE41', 16: 'CHANGE42', 17:'CHANGE43'}
        
        self.state = [0, self.max_count.loc[0,'count'], self.max_count.loc[0,'count'],  # t, A라인 max_count, B라인 max_count
                      self.order.loc[0,'BLK_1'], self.order.loc[0,'BLK_2'], self.order.loc[0,'BLK_3'], self.order.loc[0,'BLK_4'],
                      # 수요 BLK_1, 2, 3, 4
                     0, 0, 0, 
                      0, 0 ,0,
                      0] # process_time_checker, check_time_checker, change_time_checker, 
                        # process_time checker2 , check_time_checker2 change_time_checker2 state1 , 2 총 15개 
                    #state 에서 0이면 chagne, check, stop이고 process 면 1 ,2, 3,4
        self.action1 = 'CHECK'  # A 라인 액션
        self.action2 = 'CHECK' # B 라인 액션

    def reset():
        state = [0, self.max_count.loc[0,'count'], self.max_count.loc[0,'count'],  # t, A라인 max_count, B라인 max_count
                      self.order.loc[0,'BLK_1'], self.order.loc[0,'BLK_2'], self.order.loc[0,'BLK_3'], self.order.loc[0,'BLK_4'],
                     0, 0, 0, 
                      0, 0 ,0,
                      0]
        return state
    
    
    def get_action(output) :
        return unravel_index(output.argmax(), output.shape)
    
    
    def isprocess(action) :
        if action == 'PROCESS':
            return 1
        else :
            return 0
        
    def ischange(action) : 
        if action in ['CHANGE_12', 'CHANGE_13', 'CHANGE_14' ,'CHANGE_21','CHANGE_23','CHANGE_24','CHANGE_31','CHANGE_32','CHANGE_34','CHANGE_41','CHANGE_42','CHANGE_43']:
            return 1
        else: return 0
    
    def ischeck(action) :
        if action in ['CHECK_1','CHECK_2','CHECK_3','CHECK_4'] :
            return 1
        else : return 0
    
    def isstop(action) :
        if action == 'STOP':
            return 1
        else : return 0
                      
    def F(x, a):
        if x < a:
            return 1 - x/a
        else :
            return 0
        
        
    def step(self, action1, action2, observation): 
        state = observation
        state[0] = state[0] +1 ## 시간을 업데이트
        hour = state[0]%24 ## 하루 중 몇 시간 째야?? 0 - 23
        if hour < (state[0] -1) % 24 : # 날이 바뀌었으면
            state[1] = self.max_count.loc[state[0]//24, 'count']
            state[2] = self.max_count.loc[state[0]//24, 'count'] ## A,B 라인의 max_count 새로운 날로 초기화
        else : 
            state[1] = state[1] - isprocess(action1) * 5.5
            state[2] = state[2] - isprocess(action2) * 5.5
        
        state[3] = state[3] - (506 * isprocess(action1) * (state[13] == 1) + 506 * isprocess(action2) * (state[14] == 1))
        state[4] = state[4] - (506 * isprocess(action1) * (state[13] == 2) + 506 * isprocess(action2) * (state[14] == 2))
        state[5] = state[5] - (400 * isprocess(action1) * (state[13] == 3) + 400 * isprocess(action2) * (state[14] == 3))
        state[6] = state[6] - (400 * isprocess(action1) * (state[13] == 4) + 400 * isprocess(action2) * (state[14] == 4))
        
        if hour == 18 :
            state[3] = state[3] + self.order.loc[state[0]//24+ 1,'BLK_1']
            state[4] = state[4] + self.order.loc[state[0]//24+ 1,'BLK_2']
            state[5] = state[5] + self.order.loc[state[0]//24+ 1,'BLK_3']
            state[6] = state[6] + self.order.loc[state[0]//24+ 1,'BLK_4']
        
        state[7] = state[7] + isprocess(action1) 
        state[8] = state[8] + ischeck(action1)
        state[9] = state[9] + ischange(action1)
        
        state[10] = state[10] + isprocess(action2) 
        state[11] = state[11] + ischeck(action2)
        state[12] = state[12] + ischange(action2)
        
        if state[8] == 28:
            state[13] = int(action1[6])
            state[8] = 0
            
        if state[11] == 28:
            state[14] = int(action2[6])
            state[11] = 0
            
        if ischange(action1) ==1:
            if state[9] == int(self.change_time[(self.change_time['from'] == 'MOL_'+ action1[7]) & (self.change_time['to'] == 'MOL_' + action1[8])]['time']):
                state[13] = int(action1[8])
                state[9] = 0
                
        if ischange(self.action2) ==1:
            if state[12] == int(self.change_time[(self.change_time['from'] == 'MOL_'+ action2[7]) & (self.change_time['to'] == 'MOL_' +action2[8])]['time']):
                state[14] = int(action2[8])
                state[12] = 0
        
        if state[7] == 140 : 
            state[13] = 0
            state[7] = 0
            
        if state[10] == 140 :
            state[14] = 0
            state[10] = 0
                      
        next_state = state
        
        if t == 2184 :
            done = True
        
        p = max(self.order.loc[(state[0] // 24):, 'BLK_1'].sum() - self.production[0], 0)+ \
        max(self.order.loc[(state[0] // 24):, 'BLK_2'].sum() - self.production[1], 0)+ \
        max(self.order.loc[(state[0] // 24):, 'BLK_3'].sum() - self.production[2], 0)+ \
        max(self.order.loc[(state[0] // 24):, 'BLK_4'].sum() - self.production[3], 0)
         # 역누적 수요 -역누적 생산량 = 부족분
            
        q = max(self.production[0] - self.order.loc[(self.state[0] // 24):, 'BLK_1'].sum(), 0)+ \
        max(self.production[1] - self.order.loc[(self.state[0] // 24):, 'BLK_2'].sum(), 0)+ \
        max(self.production[2] - self.order.loc[(self.state[0] // 24):, 'BLK_3'].sum(), 0)+ \
        max(self.production[3] - self.order.loc[(self.state[0] // 24):, 'BLK_4'].sum(), 0) 

        self.checker2[0] = self.checker2[0] + ischagne(action1) + ischange(action2)
        c = self.checker2[0]
        self.checker2[2] = self.checker2[2] + isstop(action1) + isstop(action2)
        s = self.checker2[2]
        
        N = self.order.loc[(state[0]//24):, ['BLK_1','BLK_2','BLK-3','BLK-4']].sum().sum()
        M = state[0]
        
        reward = 50 * F(p, 10*N) + 20 * F(q, 10*N) + 20 * F(c, M)  + 10 * F(s, M) 
        

        return next_state ,reward, done

In [ ]:
a = DGNAgent()

In [ ]:
a.create_model()

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras import datasets, layers, models

Action =  18개 = 체크 4개, change 12개, Stop Process

In [ ]:
b= [10, 11]
b[-1]

In [ ]:
class MyLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs=18):
        super(MyLayer, self).__init__()
        self.num_outputs = num_outputs


    def call(self, inputs):
        Q = inputs.numpy()[0] * 4
       #if (self.state[10] >= 1) and (self.state[10] <= 27) :
    
        return Q

layer = MyLayer()
print(layer(tf.ones([10, 5])))

In [ ]:
class OuterLayerWithKernelRegularizer(tf.keras.layers.Layer):
    def __init__(self):
        super(OuterLayerWithKernelRegularizer, self).__init__()
        self.dense = tf.keras.layers.Dense(32)

    def call(self, inputs):
        return self.dense(inputs)


layer = OuterLayerWithKernelRegularizer()
_ = layer(tf.zeros((1, 1)))

In [ ]:
_.numpy()[0]

In [ ]:
order.loc[0,'BLK_1']

In [ ]:
order

In [ ]:
1 + True

In [ ]:
def create_model() :
    model = models.Sequential()
    model.add(Conv1D(64,8, input_shape = (15,1)))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size = 4))
    model.add(Dropout(0.2))
        
    #model.add(Conv1D(32,6))
    #model.add(Activation('relu'))
    #model.add(MaxPooling1D(pool_size = 4))
    #model.add(Dropout(0.2))
        
    #model.add(Conv2D(16,(3,3)))
    #model.add(Activation('relu'))
    #model.add(MaxPooling2D(2,2))
    #model.add(Dropout(0.2))
        
    model.add(Flatten())
    model.add(Dense(64))
        
    model.add(Dense(18, activation = "relu"))
        

    return model

In [ ]:
create_model()

In [ ]:
model.summary

In [ ]:
model = models.Sequential()
model.add(Conv1D(64,8, input_shape = (15,1)))
model.add(Activation('relu'))
model.add(Dropout(0.2))
        
model.add(Conv1D(32,6))
model.add(Activation('relu'))
model.add(Dropout(0.2))
        
    #model.add(Conv2D(16,(3,3)))
    #model.add(Activation('relu'))
    #model.add(MaxPooling2D(2,2))
    #model.add(Dropout(0.2))
        
model.add(Flatten())
model.add(Dense(64))
model.add(Dense(18, activation = "relu"))

In [ ]:
model.summary()

In [ ]:
state = [0.2, 0.1, 0.3, 0.4, 0.1, 0.1, 0.1, 1, 0, 0, 0, 0, 0, 0, 0]
state = np.array(state)
state = state.reshape(-1, 15, 1)
state

In [ ]:
result = model.predict(state)

In [ ]:
result.shape

In [ ]:
result

In [ ]:
state

In [ ]:
state.argmax()

In [ ]:
action_dict = {0:'process', 1:'stop',2:'CHECK1', 3 : 'CHECK2', 4 : 'CHECK3' , 5 : 'CHECK4', 6 : 'CHANGE12', 7 : 'CHANGE13'
              ,8 : 'CHANGE14' , 9: 'CHANGE21', 10 : 'CHANGE23', 11 : 'CHANGE24', 12:'CHANGE31', 13: 'CHANGE32',14:'CHANGE34',
              15 : 'CHANGE41', 16: 'CHANGE42', 17:'CHANGE43'}

In [ ]:
action_dict[state.argmax()]

In [ ]:
order.shape